apiVersion: v1
kind: ConfigMap
metadata:
  name: microcart-config
  namespace: microcart
data:
  NODE_ENV: "production"
  PORT_GATEWAY: "4000"
  PORT_USER_SERVICE: "3001"
  PORT_PRODUCT_SERVICE: "3002"
  PORT_CART_SERVICE: "3003"
  PORT_ORDER_SERVICE: "3004"
  PORT_WISHLIST_SERVICE: "3005"
  PORT_SUPPORT_SERVICE: "3006"
  USER_SERVICE_URL: "http://user-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  CART_SERVICE_URL: "http://cart-service:3003"
  ORDER_SERVICE_URL: "http://order-service:3004"
  WISHLIST_SERVICE_URL: "http://wishlist-service:3005"
  SUPPORT_SERVICE_URL: "http://support-service:3006"
  GOOGLE_CALLBACK_URL: "http://microcart.me/api/auth/google/callback"
  FRONTEND_URL: "https://microcart.me"
---
apiVersion: v1
kind: Secret
metadata:
  name: microcart-secrets
  namespace: microcart
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgrespassword"
  JWT_SECRET: "super-secret-jwt-key-change-in-production"
  GOOGLE_CLIENT_ID: "77155637336-e6i15osultvdih4h7kl6ej33uttd23c0.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
